import { generateKeyPair, exportPublicKey, exportPrivateKey, importPrivateKey, createCredential, verifyCredential, encodeCredential, decodeCredential } from '../lib/vc';
import { getCurrentHealthState, initHealthGraph, setActiveUser } from './healthGraph';
import { loadModel, generatePreVisitSummary } from './medicalAI';
import QRCode from 'qrcode';
import { meshOrchestrator } from './meshOrchestrator';
import { addPassportShare, addPassportScan } from '../lib/idb';

let keyPair = null;
let modelLoaded = false;

export async function initPassport(userId?: string, passphrase = 'vita-demo-2026'): Promise<void> {
  await initHealthGraph();
  // Only set active user if userId is provided (preserves current user for dev/bypass scenarios)
  if (userId !== undefined) {
    await setActiveUser(userId, passphrase);
  }
  await ensureKeyPair();
  try {
    await loadModel();
    modelLoaded = true;
  } catch (err) {
    console.warn('AI model not yet loaded; will load on demand');
  }
}

async function ensureKeyPair() {
  if (keyPair) return keyPair;

  const stored = localStorage.getItem('passport_key_pair');
  if (stored) {
    try {
      const { publicKey, privateKey } = JSON.parse(stored);
    } catch (e) {
      console.warn('Failed to import saved key pair, generating new one');
    }
  }

  keyPair = await generateKeyPair();
  const publicKeyBytes = await exportPublicKey(keyPair);
  const privateKeyBytes = await exportPrivateKey(keyPair);

  try {
    localStorage.setItem('passport_key_pair', JSON.stringify({
      publicKey: Array.from(publicKeyBytes),
      privateKey: Array.from(privateKeyBytes),
    }));
  } catch (e) {
    console.warn('Could not save key pair to localStorage');
  }

  return keyPair;
}

export async function getPatientDid() {
  if (!keyPair) await ensureKeyPair();
  const publicKeyBytes = await exportPublicKey(keyPair);
  return publicKeyToDid(publicKeyBytes);
}

export async function generatePassport(specialistType, userId) {
  const healthState = getCurrentHealthState();

  let summaryText;
  if (modelLoaded) {
    summaryText = await generatePreVisitSummary(healthState, specialistType);
  } else {
    summaryText = generateSimpleSummary(healthState, specialistType);
  }

  const claims = {
    healthSummary: {
      specialist: specialistType,
      generatedAt: new Date().toISOString(),
      summary: summaryText,
      conditions: healthState.conditions,
      medications: healthState.medications,
      allergies: healthState.allergies,
      encounters: healthState.encounters.slice(-5),
    },
  };

  const patientDid = await getPatientDid();
  if (!keyPair) await ensureKeyPair();

  const vc = await createCredential({
    issuerDid: patientDid,
    subjectDid: patientDid,
    claims,
    privateKey: keyPair.privateKey,
  });

  const vcJson = encodeCredential(vc);

  const qrDataURL = await new Promise((resolve, reject) => {
    QRCode.toDataURL(
      vcJson,
      { errorCorrectionLevel: 'H', width: 512, margin: 2 },
      (err, url) => {
        if (err) reject(err);
        else resolve(url);
      }
    );
  });

  await addPassportShare({
    userId,
    specialistType,
    credential: vc,
    qrDataUrl: qrDataURL,
    timestamp: new Date().toISOString(),
  });

  meshOrchestrator.recordSearch(`passport:${specialistType}`);

  return {
    credential: vc,
    qrDataURL,
    summaryText,
  };
}

export async function importCredential(jsonString, clinicianId) {
  let vc;
  try {
    vc = decodeCredential(jsonString);
  } catch (e) {
    return { isValid: false, reason: 'Invalid JSON' };
  }

  const verification = await verifyCredential(vc);
  if (!verification.valid) {
    return { isValid: false, reason: verification.reason || 'Signature invalid' };
  }

  const claims = vc.credentialSubject;

  if (clinicianId) {
    await addPassportScan({
      clinicianId,
      patientDid: vc.credentialSubject.id,
      summary: claims.healthSummary?.summary,
      specialistType: claims.healthSummary?.specialist,
      timestamp: new Date().toISOString(),
    });
  }

  return {
    isValid: true,
    claims,
    vc,
  };
}

function generateSimpleSummary(healthState, specialistType) {
  const { conditions, medications, allergies, encounters } = healthState;

  let summary = `Pre-visit summary for ${specialistType}.\n\n`;

  if (conditions.length > 0) {
    summary += 'Active conditions: ' + conditions.map(c => c.name).join(', ') + '.\n';
  }
  if (medications.length > 0) {
    summary += 'Current medications: ' + medications.map(m => `${m.name} (${m.dose})`).join(', ') + '.\n';
  }
  if (allergies.length > 0) {
    summary += 'Allergies: ' + allergies.map(a => `${a.substance} (${a.reaction})`).join(', ') + '.\n';
  }
  if (encounters.length > 0) {
    const last = encounters[encounters.length - 1];
    summary += `Most recent visit: ${last.date} at ${last.facilityName} for ${last.reason}.\n`;
  }

  summary += '\nGenerated by VitaChain Health Passport.';
  return summary;
}

export async function getPublicKeyDid() {
  if (!keyPair) await ensureKeyPair();
  const publicKeyBytes = await exportPublicKey(keyPair);
  return publicKeyToDid(publicKeyBytes);
}
